name: online_classroom_frontend
description: A Flutter app for Online Classroom Management

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true